### PR TITLE
Direct results access

### PR DESCRIPTION
**Pull request by reedstrm**
Remove AsyncResult calls from content_status page
    
    loading the AnsyncResults is causing the content-status page to take
    almost a minute! to load for 100 results. By using the celery_task_meta
    table directly, the entire page renders instantly. I suspect it's an
    issue with the layers of abstraction: Celery is using sqlalchemy in full-on 
    ORM mode, and AsnyResult returns a "heavy" object with more
    info than we need. I timed it: 0.5 sec vs 50 sec. 100 fold - the page render time is
    almost completely the AsnyResults lookups.

~I think this is a low-risk use of this info - the table is likely to only get more information,
rather than less with future version of celery. All the attributes we need are broken out
as columns. If the storage every changes, it's straightforward to revert to calling the API.~

I investigated how celery stores task objects - the alternative might be to use a 
different backend that fetches faster, but the trade off are all either deployment
complexity (another server of some sort) or persistence (in memory storage)

### CODE REVIEW

**Comment by reedstrm** [comment]
While I agree that "going behind the back" of the API is not the best way to do this, I think I addressed most of your concerns in the commit message:

**Comment by karenc** [comment]
I believe the in-flight information can be retrieved through the State object.

**Comment by karenc** [comment]
I'm not sure which suggested solutions are too slow?  Do you mean it will take too long to implement?

**Comment by reedstrm** [comment]
Digging into this more - seems by and large, people throw away the results objects, particularly historical. Both of the monitors above do not load the history of results from before their start (even through the API allows for it), so they show empty events (nothing currently baking). Even though it galls me, I think the right answer is probably to go ahead and store the parts of the result we want in our own table, at completion, then use AsynResult to lookup any that are 'in flight'. That should limit us to smallish number of expensive lookups, bounded by how many worker threads we have running

**Comment by reedstrm** [comment]
Retrieving 100 historical AsnycResult objects takes 50 sec. Fetching from the db takes 0.5 sec for the entire page load - just the SQL part is < 100 ms.

**Comment by reedstrm** [comment]
That's the whole reason I did this.

**Comment by reedstrm** [comment]
I'm still working on a non-direct way to do this. But we just had a real-world example of needed this where speed mattered. I've set up a ssh DB tunnel to production DB and run this code locally. Here's the comparison for loading the content-status page:
```
reedstrm@sensei:~$ time curl "https://cnx.org/a/content-status/?status" >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 75191  100 75191    0     0    627      0  0:01:59  0:01:59 --:--:-- 21781

real	1m59.838s
user	0m0.055s
sys	0m0.052s
reedstrm@sensei:~$ time curl "http://localhost:6545/a/content-status/?status" >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 75234  100 75234    0     0   109k      0 --:--:-- --:--:-- --:--:--  109k

real	0m0.677s
user	0m0.000s
sys	0m0.010s
```
2 minutes caused the user (Alina) to report that there was something wrong with the page.

**Comment by karenc** [comment]
Yes, I viewed the page yesterday as well and couldn't get it to load most of the time.  Let's just store the state in our table.  That would be completely acceptable to me and should be as fast as what you have right now?

**Comment by reedstrm** [comment]
i agree that we need to store that info directly. That's going to be at least a days worth of work to do the schema change and touch all the spots needed to update that and add tests. As it happens, I need to do that same work to start tracking things that we _can't_ get from celery - history of changes of steps. I'd like to do a not-rushed job on that, so as a compromise, can we merge this as an "ugly bugfix"  for the speed issue?  I'll work on replacing it with a more full-tracking version, which I probably won't get done for this release.

**Comment by karenc** [comment]
Ok, in that case, let's merge this, have a PR for reverting this so we can start from scratch for using our own tables.

**Comment by reedstrm** [comment]
something weird happened w/ the rebase: this _was_ one commit.

**Comment by reedstrm** [comment]
reset to master and cherry-picked the single commit. Let's see if that works better.

**Comment by reedstrm** [comment]
So, single commit, all tests pass. @karenc we good to merge?

**Pull request merged**
