### PR TITLE
WIP: add cnx-publishing-builds as a dependency to cnx-publishing

### PR DESCRIPTION
**Pull request by mwharrison**
I'm adding this dependency, but this should be merged until cnx-publishing-builds is finished.

### CODE REVIEW

**Comment by karenc** [comment]
Since we haven't released `cnx-publishing-builds` yet, you'll need to install it manually in `.travis.yml` for travis to find the package.

**Comment by mwharrison** [comment]
Should I make this a WIP PR until the package is complete?

**Comment by karenc** [comment]
`cnx-publishing-builds` rename pull request has already been merged, just modify `.travis.yml` to install `cnx-publishing-builds`.

**Comment by mwharrison** [comment]
Am I doing something wrong? I tried to follow how the other packages are being imported but the tests are failing.

**Comment by pumazi** [comment]
cnx-publishing-builds depends on cnx-transforms, that that needs to be added as well. :fearful:

**Comment by mwharrison** [comment]
Should that be added here, or added as a requirement to cnx-publishing-builds?

**Comment by pumazi** [comment]
It's already a requirement of cnx-publishing-builds, which is why the travis build is currently failing. The issue at the moment is that it can't resolve the package named 'cnx-transforms' because it's not installed or on a known package index (i.e. PyPI). So, you'll need to add it here.

Perhaps we can make this easier? We so rarely touch these files, but it's now going to be a big mess because this change will cascade into the cnx-authoring travis build too... :frowning:

**Comment by mwharrison** [comment]
It does seem like this could be done better, I'm still not clear on why if a package has a requirement that's installed it doesn't install that with itself and make travis pass.

**Comment by pumazi** [comment]
Can we make this builds API an **optional** part of publishing?

To answer my own question, I think so. The exports are a secondary and side process. Also, it means that local dev builds of the apps won't need all the moving parts that for transformation services.

So... perhaps we can include cnx-publishing-builds as a configuration include (that is within the ini under ``pyramid.include = ``)? :grimacing:

**Comment by pumazi** [comment]
@mwharrison the package is a dependency/requirement and setuptools looks to resolve that requirement, but can't find it. Also, in our tests, we want to use the version of the dependency at master. This might need to change now that our package count has increased. If we had a released version of cnx-transforms on pypi, it would find it and move on with the installation.

We have a few options that we should discuss. They aren't related directly to this pull request, so I'll move the conversation and post an issue here when I've made it.

**Comment by pumazi** [comment]
I've created Connexions/devops#12 to discuss the issue regarding CI configuration and cascading dependency additions.

**Pull request closed without merging**
