### PR TITLE
Add a moderation interface

### PR DESCRIPTION
**Pull request by pumazi**
See also [sprint 37 card](https://trello.com/c/vHW9TWta/1149-create-backend-code-for-pending-queue).

This completes the interface and functionality for accepting/rejecting publications for first time publishers.

### CODE REVIEW

**Comment by pumazi** [comment]
```sql
ALTER TABLE publications
    ADD COLUMN created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ALTER TABLE publications
    ALTER COLUMN epub DROP NOT NULL;

ALTER TYPE publication_states
    ADD VALUE 'Waiting for moderation' AFTER 'Failed/Error';
ALTER TYPE publication_states
    ADD VALUE 'Rejected' AFTER 'Waiting for moderation';
```

BTW, pyrseas didn't notice the type alternations, nor the dropped constraint.

**Comment by pumazi** [comment]
Depends on Connexions/cnx-archive#302

**Comment by reedstrm** [comment]
Drying out the cursor is good:  I think it's on the way to making a publish even more transactional.

**Comment by reedstrm** [comment]
Confirmed on Pyrseas 7.1 missing the enum diff and the drop of null constraint.

**Comment by pumazi** [comment]
Yeah, I'm not sure how I feel about what I did here. You'll notice that it does some fancy argument things. It may cause not be future proof, but then again, what really is?

**Pull request merged**
