### PR TITLE
Tidy up content status page and add "QUEUED" to filter

### LINKED ISSUE #189: baking monitoring tool => add HTML title/ browser metadata
When I have a browser with multiple open tabs, it's often hard to find which tab had the Content Status Tool open since there's no title metadata, just the URL visible in the tab.

image

@brittweinstein Please comment with what your request for what the title of the browser tab would be, e.g. "Baking Monitoring Tool - [servername]" or whatever.

### LINKED ISSUE #193: baking monitoring tool=> filter for QUEUED jobs
On https://staging.cnx.org/a/content-status/, we had a filter on for a uuid and it did _not_ show a `QUEUED` job that was active. (Is `PENDING` the same as `QUEUED`?) In any case, there should be a working filter that shows `QUEUED` jobs when filtering by author and/or uuid.

cc @brittweinstein 

EDIT: per [this comment](https://github.com/Connexions/cnx-publishing/pull/197#issuecomment-338317607), known tasks are `QUEUED`, unknown tasks are still `PENDING`.

### PR DESCRIPTION
**Pull request by karenc**
- Change status filter checkboxes to use the same input name
- Move element inline styling to main.css
- Align the form fields and inputs
- Correct "showing" line with actual number of results returned
- Add "GOB - [servername]" as the title
- Add "QUEUED" to status filters

Close #189
Close #193

---

Content status page on QA:

content-status-old

Content status page after this PR:

content-status-new

### CODE REVIEW

**Comment by karenc** [comment]
[How do we improve monitoring status of content production?](https://trello.com/c/lAYdPZi7/242-how-do-we-improve-monitoring-status-of-content-production)

**Comment by kerwinso** [comment]
@sisiz @karenc I asked this question in #193: What is the difference between `PENDING` and  `QUEUED`?

**Comment by karenc** [comment]
@kerwinso I think from now on the jobs are just going to be `QUEUED` instead of `PENDING`.  The problem we had with `PENDING` is, even if the job doesn't exist, the status is still `PENDING`, which was really confusing..  So we added `QUEUED` instead.  We can probably remove the `PENDING` checkbox?

**Comment by kerwinso** [comment]
@karenc OK then, please remove the `PENDING` checkbox. AFAIK, `PENDING` didn't correspond to any of the baking processing messages that I'd looked at with Ross.

**Comment by reedstrm** [comment]
What happens if channel_processer is down, and publishing happens? Those are not `QUEUED`, 'cause there's nothing in the rabbitmq queue for them. PENDING is state 5 in the modulestates table. Right now we  move that to 6 PROCESSING when the notification is picked up. I asked for QUEUED to be added, not just renamed, reserving PROCESSING for 'removed from the queue, actually baking or whatever'. The biggest problem with that seems to be getting the signal into the db.

**Comment by kerwinso** [comment]
Thanks @reedstrm, I was not aware that `PENDING` was an actual state. What does it mean from a user perspective?

I think we need to agree on what the list of statuses should be. For instance, `RETRY` has no meaning for me -- from a user standpoint, it's the same as `FAILURE`.

This is my understanding of the status checkboxes that we will need for the content status tool:

- `PENDING` : @reedstrm to explain this.
- `QUEUED`: job is in the queue waiting for baking to start (baking has not started yet).
- ~~`STARTED`~~: not sure what this meant before, I would vote for calling this `PROCESSING` instead (unless they are actually 2 different states?). 
  - This means: "removed from the queue, actually baking". 
  - Note: This message is related to the request in #191 (which we probably want to update once we resolve this.)
- `FAILURE`: ruh roh, baking job failed.
- `SUCCESS`: happy happy joy joy, we all baked.

Thoughts? Any statuses missing?

cc @openstaxalina @brittweinstein @sisiz

**Comment by karenc** [comment]
@reedstrm These are not states from our database tables.  The states are from celery.  We might change the implementation to do what you said in the future, but that's not what's happening at the moment.

**Comment by reedstrm** [comment]
@karenc thanks for the clarification - I'm refreshing my knowledge of celery right now.I think it's probably wrong to bleed the bare celery states out to the users here, but it's a place to start.

**Comment by kerwinso** [comment]
@reedstrm I don't think I've ever seen STARTED show up either.
@karenc Does RETRY mean anything different from FAILURE?

**Comment by karenc** [comment]
These are the celery built in states (http://docs.celeryproject.org/en/latest/userguide/tasks.html#built-in-states):

 - `PENDING` (we changed known tasks to `QUEUED`, unknown tasks are still `PENDING`)
   Task is waiting for execution or unknown. Any task id that’s not known is implied to be in the pending state.

 - `STARTED` (I guess we don't have this enabled)
   Task has been started. Not reported by default, to enable please see app.Task.track_started.

 - `SUCCESS`
   Task has been successfully executed.

 - `FAILURE`
   Task execution resulted in failure.

 - `RETRY` (I think if the item is not latest in the bake queue, it will be "retried" in the deferred queue)
   Task is being retried.

 - `REVOKED` (This is probably only done using the rabbitmq admin command)
   Task has been revoked.

**Comment by kerwinso** [comment]
Thanks for clarifying @karenc. I say let's enable `STARTED` and we good to go.

**Comment by karenc** [comment]
@kerwinso Could you add another issue for that please?  This PR is mostly about cleaning up the content status page UI and code.

**Comment by kerwinso** [comment]
@karenc Done, I updated #191 accordingly to request displaying the `STARTED` state.

**Pull request merged**
